services:
  dns-server:
    image: technitium/dns-server:latest
    container_name: dns99
    network_mode: host
    environment:
      - DNS_SERVER_DOMAIN=dns99 #The primary domain name used by this DNS Server to identify itself. 
    volumes:
      - ./config:/etc/dns
    restart: unless-stopped
